### ISSUE TITLE
module 'comfy.model_management' has no attribute 'unload_model_clones'

### ISSUE THREAD

**Issue by jackqn** [huchenlei/ComfyUI-layerdiffuse#115]
I obtained the correct results when using the SDXL model
When I was using the 1.5 model, an error occurred
module 'comfy.model_management' has no attribute 'unload_model_clones'
got prompt
!!! Exception during processing !!!  module 'comfy.model_management' has no attribute 'unload_model_clones'
Traceback (most recent call last):
File "G:\jack\ComfyUI\execution.py", line 328, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\jack\ComfyUI\execution.py", line 203, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\jack\ComfyUI\execution.py", line 174, in _map_node_over_list
process_inputs(input_dict, i)
File "G:\jack\ComfyUI\execution.py", line 163, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\jack\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\layered_diffusion.py", line 362, in apply_layered_diffusion
return ld_model.apply_layered_diffusion_attn_sharing(model)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\jack\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\layered_diffusion.py", line 288, in apply_layered_diffusion_attn_sharing
patcher = AttentionSharingPatcher(
^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\jack\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\lib_layerdiffusion\attention_sharing.py", line 330, in __init__
model_management.unload_model_clones(unet)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.model_management' has no attribute 'unload_model_clones'

**Comment by GeminiSquishGames** [comment]
Same here. It seemed to work fine a few updates ago but my workflows for 1.5 are broken.

**Comment by sjsdwwy** [comment]
> 这里也是一样。几次更新前它似乎运行良好，但我的 1.5 工作流程坏了。

Is it solved? I also reported the same error.

**Comment by huchenlei** [comment]
Confirmed broken by https://github.com/comfyanonymous/ComfyUI/pull/5450/

**Comment by GeminiSquishGames** [comment]
I'm still getting the error. I'll have to open a new issue I guess.

**Comment by Xiaoxian3570** [comment]
Hey buddy, so what's the situation now? I have the same problem too!

![Image](https://github.com/user-attachments/assets/49f78a31-dc48-44ea-ae5d-df821840cc5c)

**Comment by Xiaoxian3570** [comment]
So I didn't update haha, it seems like I've already solved it
nice！！！
![Image](https://github.com/user-attachments/assets/0f513a94-410b-435d-b620-86bda62dbb9b)

![Image](https://github.com/user-attachments/assets/5e6075a7-d737-4d04-9346-14384d17e131)

**Comment by Xiaoxian3570** [comment]
It's strange, I encountered another problem. I just changed the dog to a girl, and he made an error. When it was a dog in front of me, he wouldn't make an error!!??
![Image](https://github.com/user-attachments/assets/5802754f-ee69-484b-9bad-582e913e1e94)

![Image](https://github.com/user-attachments/assets/1076d167-5937-4187-b60d-75d0ac8f832d)

**Comment by Xiaoxian3570** [comment]
I know how to solve it, but it's troublesome. I can't change keywords on a workflow that is already working properly, otherwise it will cause errors. Every time I need to change keywords, I need to build a new workflow to avoid errors,
What I mean is that this workflow is one-time He can only work on one prompt word and cannot modify it!
![Image](https://github.com/user-attachments/assets/1685bbac-1b9d-4d9f-b21d-29a1b24de1d2)

![Image](https://github.com/user-attachments/assets/de26599e-90f5-4fe8-8c4c-7d743454c7a7)
